import = [
	"~/.config/alacritty/themes/themes/dracula.toml"
]

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.8

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[keyboard]
bindings = [
	{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
